[tools]
# Compiler invocation expressed as a list of tokens
cpp_compiler = ["uv", "run", "python", "-m", "ziglang", "c++"]

[flags]
# GNU-style flags; the build system will translate as needed
compiler_flags = ["-std=gnu++17", "-fpermissive", "-Wall", "-Wextra"]
# Choose platform-defines appropriate for your use case (e.g., STUB_PLATFORM or __EMSCRIPTEN__)

defines = ["STUB_PLATFORM", "__EMSCRIPTEN__"]
include_paths = ["src"]
# System include paths (treated as -isystem)
system_include_paths = [
  "src/platforms/stub"
]
