name: AVR Simulation Tests (simavr)

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'examples/Test/**'
      - '.github/workflows/avr_simavr.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'examples/Test/**'
      - '.github/workflows/avr_simavr.yml'

permissions:
  contents: read
  actions: read
  id-token: write
  pull-requests: read

jobs:
  simavr-math8-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install AVR toolchain and simavr
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-avr \
            avr-libc \
            simavr

      - name: Pin Python version
        run: echo "3.11" >> .python-version

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "**/pyproject.toml"
          version: "0.8.0"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Compile Test.ino for Arduino Uno
        run: |
          set -e
          uv run ci/ci-compile.py uno --examples Test

          # Find the compiled .elf file
          ELF_FILE=$(find .build -name "*.elf" | head -n 1)
          if [ -z "$ELF_FILE" ]; then
            echo "ERROR: Could not find compiled .elf file"
            exit 1
          fi

          echo "Found ELF file: $ELF_FILE"

          # Copy to known location for simavr
          mkdir -p build
          cp "$ELF_FILE" build/Test.elf

          # Show file info
          ls -lh build/Test.elf
          avr-size build/Test.elf

      - name: Run tests in simavr
        id: run_simavr
        run: |
          set -e

          # Run simavr with UART output to file
          # -m atmega328p: ATmega328P (Arduino Uno)
          # -f 16000000: 16MHz clock
          # -t: Run for specified number of cycles (16MHz * 10 seconds = 160M cycles)
          timeout 15 simavr \
            -m atmega328p \
            -f 16000000 \
            build/Test.elf \
            > simavr_output.txt 2>&1 || true

          echo "=== Simavr Output ==="
          cat simavr_output.txt
          echo "=== End Simavr Output ==="

      - name: Validate test results
        run: |
          set -e

          # Check for test completion
          if ! grep -q "Test Summary:" simavr_output.txt; then
            echo "ERROR: Tests did not complete"
            exit 1
          fi

          # Check for failures
          if grep -q "Failed: [1-9]" simavr_output.txt; then
            echo "ERROR: Some tests failed"
            grep "FAIL" simavr_output.txt || true
            exit 1
          fi

          # Check for successful completion
          if grep -q "All tests PASSED!" simavr_output.txt; then
            echo "SUCCESS: All AVR math8 assembly tests passed!"
            exit 0
          fi

          echo "ERROR: Could not determine test status"
          exit 1

      - name: Upload simavr output on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: simavr-output-${{ github.sha }}
          path: |
            simavr_output.txt
            build/Test.elf
