name: unit tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: ["gcc", "clang"]
    
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install uv
      

      - name: Install
        run: ./install
        shell: bash

      - name: Add gcc for linux
        if: runner.os == 'Linux' && matrix.compiler == 'gcc'
        run: sudo apt-get install gcc

      - name: Add gcc for macos
        if: runner.os == 'macOS' && matrix.compiler == 'gcc'
        run: brew install gcc

      - name: Install LLVM for Linux
        if: runner.os == 'Linux' && matrix.compiler == 'clang'
        run: sudo apt-get install llvm

      - name: Install LLVM for macOS
        if: runner.os == 'macOS' && matrix.compiler == 'clang'
        run: |
          brew install llvm
          echo "/usr/local/opt/llvm/bin" >> $GITHUB_PATH

      - name: Install LLVM for Windows
        if: runner.os == 'Windows' && matrix.compiler == 'clang'
        run: |
          choco install llvm

      - name: Run Test
        run: |
          if [ "${{ matrix.compiler }}" = "clang" ]; then
            ./test --clang
          else
            ./test
          fi
        shell: bash

      - name: Run Test
        if: runner.os != 'Linux'
        run: ./test
        shell: bash
