name: unit tests

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'tests/**'
      - 'ci/**'
      - '.github/workflows/**'
      - 'CMakeLists.txt'
      - 'test'
      - 'test.py'
  pull_request_target:
    branches:
      - master
    paths:
      - 'src/**'
      - 'tests/**'
      - 'ci/**'
      - '.github/workflows/**'
      - 'CMakeLists.txt'
      - 'test'
      - 'test.py'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: ["gcc", "clang"]
    
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"
      

      - name: Install
        run: ./install
        shell: bash

      - name: No namespace after headers
        run: |
          uv run python ci/tests/no_using_namespace_fl_in_headers.py


      
      - name: Run Example Blink
        run: |
          ./test --no-parallel --no-unity --examples blink --no-pch --verbose

      - name: Run Unit Test Json
        run: |
          ./test --no-parallel --no-unity --unit --no-pch --verbose Json

      - name: Run All Unit Tests
        run: |
          if [ "${{ matrix.compiler }}" = "clang" ]; then
            ./test --clang --no-parallel --unit--verbose
          else
            ./test --no-parallel --unit --verbose
          fi
        shell: bash

      - name: Run All Examples
        run: |
          if [ "${{ matrix.compiler }}" = "clang" ]; then
            ./test --clang --no-parallel --examples --verbose
          else
            ./test --no-parallel --examples --verbose
          fi
        shell: bash
