name: build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  get_supported_boards:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get supported boards
        run: |
          echo "Supported boards:"
          ./compile --supported-boards > supported_boards.txt
        shell: bash
      - name: Upload supported boards
        uses: actions/upload-artifact@v3
        with:
          name: supported-boards
          path: supported_boards.txt

  build:
    runs-on: ubuntu-latest
    needs: get_supported_boards
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Download supported boards
        uses: actions/download-artifact@v3
        with:
          name: supported-boards

      - name: Read supported boards and trigger builds
        run: |
          while IFS= read -r board; do
            echo "Building for board: $board"
            # Call the build_template.yml with the current board as an argument.
            gh workflow run ./.github/workflows/build_template.yml --field args="$board"
          done < supported_boards.txt
        shell: bash
