name: Build Template

on:
  workflow_call:
    inputs:
      args:
        type: string
        required: false
        default: ""


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO build dependencies
        run: |
          pip install -r ci/requirements.txt

      # disabled for now.
      #- name: Cache .build directory
      #  uses: actions/cache@v3
      #  with:
      #    path: ./.build
      #    key: ${{ runner.os }}-build-${{ hashFiles('./ci/**') }}
      #    restore-keys: |
      #      ${{ runner.os }}-build-

      - name: Build FastLED examples
        run: |
          set -o pipefail
          python ./ci/ci-compile.py ${{ inputs.args }} | tee build.log
        shell: bash

      - name: Upload build artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ inputs.args }}-${{ github.run_number }}-${{ github.run_attempt }}-${{ github.sha }}
          path: .build/
          include-hidden-files: true

      - name: Upload build log
        uses: actions/upload-artifact@v4
        with:
          name: build-log-${{ inputs.args }}-${{ github.run_number }}-${{ github.run_attempt }}-${{ github.sha }}
          path: build.log

      - name: Check build status
        if: failure()
        run: exit 1
