name: build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  get_supported_boards:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get supported boards
        run: |
          echo "Supported boards:"
          ./compile --supported-boards > supported_boards.txt
        shell: bash
      - name: Upload supported boards
        uses: actions/upload-artifact@v3
        with:
          name: supported-boards
          path: supported_boards.txt

  build:
    runs-on: ubuntu-latest
    needs: get_supported_boards
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Download supported boards
        uses: actions/download-artifact@v3
        with:
          name: supported-boards

      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y
        shell: bash

      - name: Read supported boards and trigger builds
        run: |
          while IFS= read -r board; do
            echo "Building for board: $board"
            gh workflow run ./.github/workflows/build_template.yml --field args="$board"
          done < supported_boards.txt
        shell: bash
