name: wasm compilers

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build WASM Compiler
      run: ./wasm --build_wasm_compiler

    - name: Upload Artifacts
      run: |
        for file in dist/*; do
          if [ -f "$file" ]; then
            filename=$(basename "$file")
            echo "Uploading $filename"
            gh release upload "$GITHUB_REF" "$file" --clobber
          fi
        done
