name: ESP32-C2 Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    uses: ./.github/workflows/build_template_custom_board.yml
    with:
      board: esp32-c2-devkitm-1

