name: build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build_uno:
    uses: ./.github/workflows/build_template.yml
    with:
      args: "uno"

  build_esp32dev:
    uses: ./.github/workflows/build_template.yml
    with:
      args: "esp32dev"

  build_esp01:
    uses: ./.github/workflows/build_template.yml
    with:
      args: "esp01"

  build_esp32_c3_devkitm_1:
    uses: ./.github/workflows/build_template.yml
    with:
      args: "esp32-c3-devkitm-1"

  build_esp32_s3_devkitc_1:
    uses: ./.github/workflows/build_template.yml
    with:
      args: "esp32-s3-devkitc-1"

  build_yun:
    uses: ./.github/workflows/build_template.yml
    with:
      args: "yun"

  build_digix:
    uses: ./.github/workflows/build_template.yml
    with:
      args: "digix"

  build_teensy30:
    uses: ./.github/workflows/build_template.yml
    with:
      args: "teensy30"

  build_teensy41:
    uses: ./.github/workflows/build_template.yml
    with:
      args: "teensy41"
