name: apollo3_red

on:
  push:
    branches:
      - master


jobs:
  build:
    uses: ./.github/workflows/build_template.yml
    with:
      args: apollo3_red
      platform: git+https://github.com/nigelb/platform-apollo3blue
