name: esp32c2

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:

  prebuild:
    uses: ./.github/workflows/build_template.yml
    with:
      board: uno

  copy_boards:
    runs-on: ubuntu-latest
      steps:
        - name: Copy ci/boards/*.json to ~/.platformio/boards
          run: |
            mkdir -p ~/.platformio/boards
            cp ci/boards/*.json ~/.platformio/boards

  build:
    uses: ./.github/workflows/build_template.yml
    with:
      board: esp32-c2-devkitm-1
