name: check_stm32f103c8_bluepill_size

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'examples/**'
      - 'ci/**'
      - '.github/workflows/check_bluepill_size.yml'
      - '.github/workflows/build_template_binary_size.yml'
      - 'CMakeLists.txt'
      - 'platformio.ini'
      - 'library.json'
      - 'library.properties'
  pull_request_target:
    branches:
      - master
    paths:
      - 'src/**'
      - 'examples/**'
      - 'ci/**'
      - '.github/workflows/check_bluepill_size.yml'
      - '.github/workflows/build_template_binary_size.yml'
      - 'CMakeLists.txt'
      - 'platformio.ini'
      - 'library.json'
      - 'library.properties'

jobs:
  build:
    uses: ./.github/workflows/build_template_binary_size.yml
    with:
      board: stm32f103c8_bluepill
      max_size: 55000
      max_size_apa102: 45000
